apiVersion: v1
kind: Service
metadata:
  name: scot4-flair-db-service
spec:
  ports:
  - port: {{ .Values.scot4.flair.database.containerPort }}
  selector:
    app: scot4-flair-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scot4-flair-db
spec:
  selector:
    matchLabels:
      app: scot4-flair-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scot4-flair-db
        {{- if .Values.scot4.forcePodRedeploy }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
    spec:
      containers:
      - image: "{{ .Values.scot4.flair.database.repository }}:{{ .Values.scot4.flair.database.tag }}"
        name: scot4-flair-db
        envFrom:
        - configMapRef:
            name: scot4-flair-db-env-config
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scot4-flair-secrets
                key: ROOT_DB_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scot4-flair-secrets
                key: FLAIR_DB_PASSWORD
        ports:
        - containerPort: {{ .Values.scot4.flair.database.containerPort }}
          name: scot4-flair-db
        volumeMounts:
        - name: mysql-flair-data-storage
          mountPath: /var/lib/mysql
        - name: scot4-flair-db-config-file
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-flair-data-storage
        persistentVolumeClaim:
          claimName: mysql-flair-data-pv-claim
      - name: scot4-flair-db-config-file
        configMap:
          name: scot4-flair-db-config-file
